name: Build and deploy container app to Azure Web App - ctseassignment1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # --- Snyk CLI Setup ---
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@0.4.0
        with:
          version: latest
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # --- Run Snyk Test (non-blocking) ---
      - name: Run Snyk vulnerability scan
        run: |
          snyk test --json > snyk-results.json
          cat snyk-results.json

          high_count=$(jq '[.vulnerabilities[] | select(.severity=="high" or .severity=="critical")] | length' snyk-results.json)

          if [ "$high_count" -gt 0 ]; then
            echo "❌ High/critical severity vulnerabilities found: $high_count"
            sleep 1
            exit 1
          else
            echo "✅ No high/critical severity issues found. Continuing..."
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/ctseassignment1:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ctseassignment1'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/ctseassignment1:${{ github.sha }}'
